# Prerequisites
#
# sudo dnf install ansible
# git clone https://github.com/daveyorke/ansible_pull.git
# ansible-galaxy collection install community.general
# ansible-galaxy collection install community.crypto
# ansible-pull -K -U https://github.com/daveyorke/ansible_pull.git
#

- hosts: localhost
  connection: local
  tasks:
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    become: true


- hosts: localhost
  connection: local
  tasks:
  - name: Install some psutil python dependency for dconf
    ansible.builtin.pip:
      name: psutil
    when: ansible_facts['hostname'] == "neon"
    become: true

#- hosts: localhost
#  connection: local
#  tasks:
#  - name: install dropbox
#    ansible.builtin.dnf:
#      name: roles/common/files/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
#      state: present
#      disable_gpg_check: true
#    become: true


- hosts: localhost
  connection: local
  roles:
    - role: common
    - role: ssh
    - role: gnome
    - role: dotfiles
    - role: timeshift
    - role: virtualization
    - role: steam


