# Prerequisites
# - ansible
# - community.general collection
#
#

- hosts: localhost
  connection: local

#  pre_tasks:
#    - name: update repositories
#      apt:
#        update_cache: yes
#      changed_when: False

  tasks:
  - name: Install community.general collection
    ansible.builtin.pip:
      name: psutil
    when: ansible_facts['hostname'] == "neon"
    become: true
    
  - name: Install some psutil python dependency for gconf
    ansible.builtin.pip:
      name: psutil
    when: ansible_facts['hostname'] == "neon"
    become: true

  - name: Install htop
    ansible.builtin.dnf:
      name: htop
      state: present
    when: ansible_facts['hostname'] == "neon"
    become: true
    
  - name: Install timeshift
    ansible.builtin.dnf:
      name: timeshift
      state: present
    when: ansible_facts['hostname'] == "neon"
    become: true
    
  - name: Take first snapshot backup
    ansible.builtin.shell:
      cmd: timeshift --create --comment "Initial snapshot"
    when: ansible_facts['hostname'] == "neon"
    become: true

  - name: Setup gnome
    dconf:
      key: "/org/gnome/mutter/experimental-features"
      value: "['variable-refresh-rate','scale-monitor-framebuffer']"
    when: ansible_facts['hostname'] == "neon"
  
  - name: Swap CAPS and ESC
    dconf:
      key: "/org/gnome/desktop.input-sources.xkb-options"
      value: "['caps:swapescape']"
    when: ansible_facts['hostname'] == "neon"


  #  - include: tasks/users.yml
  #  - include: tasks/cron.yml
  #  - include: tasks/packages.yml
  
  #- hosts: servers
  #  roles:
  #  - common
  #  - server 
