- name: Install virtualization and vagrant
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "@virtualization" }
    - { name: "vagrant" }
    - { name: "vagrant-libvirt" }
    - { name: "kubernetes-client" }
  when: ansible_facts['hostname'] == "neon"
  become: true
  tags:
    - virt

- name: Start and enable libvirtd
  ansible.builtin.systemd_service:
    name: libvirtd
    enabled: true
    state: started
  become: true
  tags:
    - virt

- name: ensure /dev/sda1 is mounted to ~/lab
  ansible.posix.mount:
    path: /home/dave/lab
    src: /dev/sda1
    fstype: ext4
    state: mounted
  become: true
  tags:
    - virt

- name: add dave to libvirt group
  ansible.builtin.user:
    name: dave
    groups: libvirt
    append: yes
  become: true
  tags:
    - virt

- name: install minikube from remote repo
  ansible.builtin.dnf:
    name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    state: present
    disable_gpg_check: true
  become: true
  tags:
    - virt

- name: Install Podman Desktop
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "io.podman_desktop.PodmanDesktop" }
  when: ansible_facts['hostname'] == "neon"
  become: true

