- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "htop" }
    - { name: "btop" }
    - { name: "vim" }
    - { name: "screenfetch" }
    - { name: "vifm" }
    - { name: "eza" }
    - { name: "google-chrome-stable" }
    - { name: "fzf" }
    - { name: "wol" }
    - { name: "dnf-plugins-core" }
    - { name: "libappindicator-gtk3" }
  when: ansible_facts['hostname'] == "neon"
  become: true

- name: Set vim as default editor
  ansible.builtin.dnf:
    name: vim-default-editor
    state: present
    allowerasing: true
  when: ansible_facts['hostname'] == "neon"
  become: true

- name: Install flatpaks
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: "md.obsidian.Obsidian" }
    - { name: "com.valvesoftware.Steam" }
    - { name: "com.valvesoftware.Steam.CompatibilityTool.Proton-GE" }
    - { name: "com.todoist.Todoist" }
    - { name: "com.obsproject.Studio" }
  when: ansible_facts['hostname'] == "neon"
  become: true

- name: install dropbox
  ansible.builtin.dnf:
    name: https://linux.dropboxstatic.com/packages/fedora/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
    #name: roles/common/files/nautilus-dropbox-2024.04.17-1.fc39.x86_64.rpm
    state: present
    disable_gpg_check: true
  become: true
  ignore_errors: true
  tags:
    - dropbox

- name: delete home folder subdirectories and create symlinks to Dropbox
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/{{ item.name }}"
    state: absent
  with_items:
    - { name: "Desktop" }
    - { name: "Documents" }
    - { name: "Downloads" }
    - { name: "Music" }
    - { name: "Photos" }
    - { name: "Pictures" }
    - { name: "Videos" }
  tags:
    - dropbox

- name: create symlinks to ~/Dropbox/*
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/Dropbox/{{ lookup('env', 'USER') }}/{{ item.name }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.name }}"
    state: link
    force: yes
  with_items:
    - { name: "Desktop" }
    - { name: "Documents" }
    - { name: "Downloads" }
    - { name: "Music" }
    - { name: "Photos" }
    - { name: "Pictures" }
    - { name: "Videos" }
  tags:
    - dropbox
